import React from 'react';
import {connect} from 'react-redux';
import classes from './App.module.scss';

import Navigation from './components/Navigation/Navigation';
import {routeToView as views} from './state/routes';


const App = ({route}) => {
    const routeType = route.type; //props.route.type; state.location.type
    const View = views[routeType];
    
    return (    
    <div>
      <Navigation />
      <div className={classes.View}>
        <View />
      </div>
      
    </div>
    
  );
}

const mapStateToProps = state => ({
  route: state.location, //an object with e.g. pathname, payload, prev, routesMap, type
})

export default connect(mapStateToProps)(App);

/**
 * have state with location - that is generated by redux-first-router
 * we get it as props.route from mapStateToProps
 * instead of using props.route -> deconstruct route from props
 * route has property type = a key obtained from routeToPath (in storeConfiguration) 
 *  for -> routeToView
 * 
 * for payload into routes
 * https://codesandbox.io/s/m76zjj924j?file=/index.js
 */